export const MATCH_ESCROW_ABI = [
  {
    type: 'function',
    name: 'createMatch',
    stateMutability: 'payable',
    inputs: [
      { name: '_opponent', type: 'address' },
      { name: '_stake', type: 'uint256' },
      { name: '_joinWindowSeconds', type: 'uint64' },
      { name: '_confirmWindowSeconds', type: 'uint64' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'joinMatch',
    stateMutability: 'payable',
    inputs: [{ name: '_matchId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'proposeWinner',
    stateMutability: 'nonpayable',
    inputs: [
      { name: '_matchId', type: 'uint256' },
      { name: '_winner', type: 'address' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'confirmWinner',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_matchId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'forfeit',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_matchId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'dispute',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_matchId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'resolveProposalTimeout',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_matchId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'finalizeResultAfterTimeout',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_matchId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'cancel',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_matchId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'adminResolve',
    stateMutability: 'nonpayable',
    inputs: [
      { name: '_matchId', type: 'uint256' },
      { name: '_winner', type: 'address' },
      { name: '_refund', type: 'bool' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'matches',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'creator', type: 'address' },
      { name: 'opponent', type: 'address' },
      { name: 'stake', type: 'uint256' },
      { name: 'token', type: 'address' },
      { name: 'createdAt', type: 'uint64' },
      { name: 'joinedAt', type: 'uint64' },
      { name: 'joinBy', type: 'uint64' },
      { name: 'confirmBy', type: 'uint64' },
      { name: 'status', type: 'uint8' },
      { name: 'creatorPaid', type: 'bool' },
      { name: 'opponentPaid', type: 'bool' },
      { name: 'proposedWinner', type: 'address' }
    ],
  },
  {
    type: 'function',
    name: 'nextMatchId',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'admin',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
] as const;
